name: Create new release
on:
  pull_request:
    types: closed

jobs:
  create-new-release:
    if: |
      startsWith(github.head_ref, 'release-v') &&
      startsWith(github.base_ref, 'main') &&
      github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2ff
        with:
          fetch-depth: 0
      - name: Create release
        run: |
          VERSION=$(echo "${{github.head_ref}}" | sed "s/^release-//")
          gh release create $VERSION --notes "Bump to $VERSION" --title "Release-$VERSION" --target "${{github.head_ref}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
