name: hello-world
on:
  pull_request:
    types: opened

jobs:
  my-job:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World test ${{ github.event.pull_request.title }}!"
      - name: Approve Pull Request
        run: echo "Hello World test ${{ github.event.pull_request.url }}!"

